config/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('common/', include('common.urls')),
    path('game/', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path, include
from .views import *

app_name = 'game'

urlpatterns = [
    path('list/', game_list, name='game_list'),
    path('attack/', attack, name='attack'),
    path('counter/<int:pk>', counter, name='counter'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('ranking/', ranking, name='ranking'),
    path('detail_ing/<int:pk>', detail_ing, name='detail_ing'),
    path('detail_defend/<int:pk>', detail_defend, name='detail_defend'),
    path('delete/<int:pk>', game_delete, name='game_delete')
]

game/models.py
from django.db import models
from common.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Game(models.Model):
    rule = models.BooleanField()
    attacker_card = models.PositiveIntegerField(validators=[MaxValueValidator(10), MinValueValidator(1)])
    defender_card = models.PositiveIntegerField(validators=[MaxValueValidator(10), MinValueValidator(1)], null=True, blank=True)
    attacker=models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True, related_name='attack_game')
    defender=models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True, related_name='defend_game')
    created_date = models.DateTimeField(default=timezone.now)

game/forms.py
import random
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from .models import Game, User

class AttackForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ["attacker_card", "defender"]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AttackForm, self).__init__(*args, **kwargs)
        self.shuffleChoices()

    def shuffleChoices(self):
        if self.request:
            random_numbers = sorted(random.sample(range(1, 11), 5))
            choices = [(str(num), str(num)) for num in random_numbers]
            self.fields['attacker_card'] = forms.ChoiceField(choices=choices, widget=forms.RadioSelect,  label="Attacker Card")


    defender = forms.ModelChoiceField(queryset=User.objects.all(), label="Defender")



class CounterForm(forms.ModelForm):
    class Meta:
        model=Game
        fields=['defender_card']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CounterForm, self).__init__(*args, **kwargs)
        self.shuffleChoices()

    def shuffleChoices(self):
        if self.request:
            random_numbers = sorted(random.sample(range(1, 11), 5))
            choices = [(str(num), str(num)) for num in random_numbers]
            self.fields['defender_card'] = forms.ChoiceField(choices=choices, widget=forms.RadioSelect,  label="defender Card")

game/views.py
import random
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AttackForm, CounterForm
from django.db.models import Q
from .models import Game
from common.models import User

def attack(request):
    if request.method == 'POST':
        game = Game()
        form = AttackForm(request.POST, instance=game)
        if form.is_valid():
            game = form.save(commit=False)
            if(game.defender != None and game.defender != request.user):
                game.attacker = request.user
                game.rule = random.randint(0, 1)
                game.save()
                return redirect('/') # 추후 detail 이동으로 수정
    else:
        game = Game()
        form = AttackForm(request=request, instance=game)
    return render(request, 'game/game_create.html', {'form': form})

def game_list(request):
    user = request.user
    #Game 객체 전부 가져오기
    games = Game.objects.filter(Q(attacker=user) | Q(defender=user)).order_by('-created_date')
    ctx = {'games':games}
    return render(request, 'game/game_list.html', ctx)

def detail(request, pk):
    game = get_object_or_404(Game, pk=pk)
    userState, userScore = checkWinner(game, request.user)
    ctx ={'game': game, 'result':userState, 'score': userScore}
    return render(request, 'game/game_detail.html', ctx)

def detail_ing(request,pk):
    game = get_object_or_404(Game, pk=pk)
    attacker = game.attacker
    defender = game.defender

    ctx ={'game':game, 'attacker': attacker, 'defender':defender}
    return render(request, 'game/game_detail_ing.html', ctx)

def ranking(request):
    user_list = User.objects.order_by('-user_score')
    if len(user_list) >= 3:
        user_list = user_list[:3]
    return render(request, 'game/game_ranking.html', {'user_list': user_list})

def checkWinner(game, user):
    userState, userScore = 2, 0
    if game.rule == True: #Bigger card win
        if game.attacker_card > game.defender_card:
            game.attacker.user_score += game.attacker_card
            game.defender.user_score -= game.defender_card
            # 1: User win, 0: User defeat 
            if (game.attacker == user):
                userState, userScore = 1, game.attacker_card
            else:
                userState, userScore = 0, -game.defender_card
        elif game.attacker_card < game.defender_card:
            game.attacker.user_score -= game.attacker_card
            game.defender.user_score += game.defender_card
            if (game.defender == user):
                userState, userScore = 1, game.defender_card
            else:
                userState, userScore = 0, -game.attacker_card
    else: # Smaller card win
        if game.attacker_card > game.defender_card:
            game.attacker.user_score -= game.attacker_card
            game.defender.user_score += game.defender_card
            if (game.defender == user):
                userState, userScore = 1, game.defender_card
            else:
                userState, userScore = 0, -game.attacker_card
        elif game.attacker_card < game.defender_card:
            game.attacker.user_score += game.attacker_card
            game.defender.user_score -= game.defender_card
            if (game.attacker == user):
                userState, userScore = 1, game.attacker_card
            else:
                userState, userScore = 0, -game.defender_card
    game.attacker.save()
    game.defender.save()
    return userState, userScore   
        
def counter(request, pk):
    game = get_object_or_404(Game, id=pk)
    if request.method == 'POST':
        form = CounterForm(request.POST, instance=game)
        if form.is_valid():
            game = form.save()
            userState, userScore = checkWinner(game, request.user)
            return render(request, 'game/game_detail.html', {'game': game, 'result':userState, 'score': userScore})            
    else:
        if game.defender_card != None:
            return redirect('game:game_list')
        form = CounterForm(request=request, instance=game)
    return render(request, 'game/game_counter.html', {'form': form, 'pk': pk})

def game_delete(request, pk):
    if request.method == 'POST':
        Game.objects.get(id=pk).delete()
    return redirect('game:game_list')

def detail_defend(request, pk):
    game = get_object_or_404(Game, pk=pk)
    return render(request, 'game/game_detail_defend.html', {'game': game})

templates/game/game_counter.html
{% extends 'base.html' %} {% block content %}
<section class="submit_container">
  <div class="submit_modal">
    <form action="{% url 'game:counter' pk%}" method="POST" class="counter-form">
      {% csrf_token %} {{form.as_p}}
      <div class="submit_center">
        <button type="submit" class="submit_btn">CounterAttack</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/game/game_create.html
{% extends 'base.html' %} {% block content %}
<section class="submit_container">
  <div class="submit_modal">
    <form action="{% url 'game:attack' %}" method="POST" class="attack-form">
      {% csrf_token %} {{form.as_p}}
      <div class="submit_center">
        <button type="submit" class="submit_btn">Attack!</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/game/game_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<section>
    <div class="detail_container">
        <div class="detail_modal">
            <div class="detail_vs_users">{{game.id}} - {{game.attacker}} VS {{game.defender}}</div>
            {% if game.rule == 0 %}
            <p>숫자가 작은 사람이 이깁니다.</p>
            {% else %}
            <p>숫자가 큰 사람이 이깁니다.</p>
            {% endif %}
            <div id="cards_container">
                <p>{{game.attacker}} : {{game.attacker_card}}</p>
                <p>{{game.defender}} : {{game.defender_card}}</p>
            </div>
                {% if result == 0 %}
                <p>결과 : 패배</p>
                {% elif result == 1 %}
                <p>결과 : 👑👑승리👑👑</p>
                {% elif result == 2 %}
                <p>결과 : 무승부</p>
                {% endif %}
                <p>점수 : {{score}}</p>
            <div class='delete_container'>
                <form action="{% url 'game:game_list'%}">
                  {% csrf_token %}
                  <button class="submit_btn">전적목록</button>
                  </form>
              </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/game/game_detail_defend.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<section>
  <div class="detail_container">
    <div class="detail_modal">
      <div class="detail_vs_users">{{game.id}} - {{game.attacker}} VS {{game.defender}}</div>
      <div class="delete_container">
        <form action="{% url 'game:counter' game.pk %}" method="get">
          {% csrf_token %}
          <button class="submit_btn">대응하기</button>
          </form>
        </div>
        <div class='delete_container'>
            <form action="{% url 'game:game_list'%}">
              {% csrf_token %}
              <button class="submit_btn">전적목록</button>
              </form>
        </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/game/game_detail_ing.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section>
  <div class="detail_container">
    <div class="detail_modal">
      <div class="detail_vs_users">{{game.id}} - {{game.attacker}} VS {{game.defender}}</div>
      <p>진행중...</p>
      <div id="score_board">
        <p>나: {{game.attacker_card}}</p>
      </div>
      <div class="delete_container">
        <form action="{% url 'game:game_delete' game.pk %}" method="post">
          {% csrf_token %}
          <button class="submit_btn">게임취소</button>
          </form>
        </div>
        <div class='delete_container'>
          <form action="{% url 'game:game_list'%}">
            {% csrf_token %}
            <button class="submit_btn">전적목록</button>
            </form>
        </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/game/game_list.html
{% extends 'base.html' %} {% load static %} {%block content%}
<!-- 게임 목록 -->

<div id="game_history_list">
  <div id="history_list_container">
    <div id="history_list_text">
      History List
    </div>
    <p id="history_list_user">현재 플레이어 : {{request.user.username}}</p>
    <ul id="history_list_sum">
      {% for game in games %}
      <li>
        <p id="history_list_content">{{game.pk}} - {{game.attacker}} VS {{game.defender}}</p>
        {% if game.defender_card != null and game.attacker_card != null %}
            {% if game.rule == 0 %}
                {% if game.attacker_card > game.defender_card %}
                  {% if game.attacker == request.user %}
                  <p>결과: 😭패배😭</p>
                  {% else %}
                  <p>결과: 👑👑승리👑👑</p>
                  {% endif %}
                {% elif game.attacker_card < game.defender_card %}
                  {% if game.attacker == request.user %}
                  <p>결과: 👑👑승리👑👑</p>
                  {% else %}
                  <p>결과: 😭패배😭</p>
                  {% endif %}
                {% elif game.attacker_card == game.defender_card %}
                <p>결과 : 😮무승부</p>
                {% endif %}
                <a class="history_list_detail" href="{% url 'game:detail' game.pk %}"> 게임정보 </a>
            {% else %}
                {% if game.attacker_card > game.defender_card %}
                  {% if game.attacker == request.user %}
                  <p>결과: 👑👑승리👑👑</p>
                  {% else %}
                  <p>결과: 😭패배😭</p>
                  {% endif %}
                {% elif game.attacker_card < game.defender_card %}
                  {% if game.attacker == request.user %}
                  <p>결과: 😭패배😭</p>
                  {% else %}
                  <p>결과: 👑👑승리👑👑</p>
                  {% endif %}
                {% elif game.attacker_card == game.defender_card %}
                <p>결과 : 😮무승부</p>
                {% endif %}
                <a class="history_list_detail" href="{% url 'game:detail' game.pk %}"> 게임정보 </a>
            {% endif %}
        {% else %}
            {% if game.attacker.username == request.user.username %}
                <form action="{% url 'game:game_delete' game.pk %}" method="post">
                {% csrf_token %}
                <p id="history_list_result">진행 중...<button class="delete_btn">게임취소</button></p>
                </form>
                <a class="history_list_detail" href="{% url 'game:detail_ing' game.pk %}">게임정보</a>
            {% else %}
                <a class="history_list_detail" href="{% url 'game:counter' game.pk %}">CounterAttack</a>
                <a class="history_list_detail" href="{% url 'game:detail_defend' game.pk %}"> 게임정보 </a>
            {% endif %}
        {% endif%}
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{%endblock%}

templates/game/game_ranking.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
    <!-- 게임 목록 -->
    <!-- 관련 css들은 submit, main에 저장해 두었음 -->
<section class="submit_container">
    <div class="submit_modal">
        <h3 id="ranking-title">Piro 명예의 전당</h3>
        <div id="ranking-123">
            {% with sorted_users=user_list|dictsortreversed:"user_score" %}
    {% for user in sorted_users|slice:":3" %}
        {% if forloop.counter == 2 %}
            {% with user2=user %}
            <div>
                <div class="ranking-text">
                    <p>{{user.username}}</p>
                    <p>{{user.user_score}}</p>
                </div>
                <div id="ranging-2">2</div>
            </div>
            {% endwith %}
        {% elif forloop.counter == 1 %}
            {% with user1=user %}
            <div>
                <div class="ranking-text">
                    <p>{{user.username}}</p>
                    <p>{{user.user_score}}</p>
                </div>
                <div id="ranging-1">1</div>
            </div>
            {% endwith %}
        {% elif forloop.counter == 3 %}
            {% with user3=user %}
            <div>
                <div class="ranking-text">
                    <p>{{user.username}}</p>
                    <p>{{user.user_score}}</p>
                </div>
                <div id="ranging-3">3</div>
            </div>
            {% endwith %}
        {% endif %}
    {% endfor %}
{% endwith %}

        </div>
        <div class="submit_center"><a href={% url 'game:game_list'%} class="to_list">전적 목록</a></div>
    </div>
</section>
{%endblock%}