common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'common'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', logout_page, name='logout'),
    path('accounts/', include('allauth.urls')),
    
]

#localhost:8000/accounts/github/login
#localhost:8000/accounts/google/login
#localhost:8000/accounts/naver/login
#localhost:8000/accounts/kakao/login

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('common/', include('common.urls')),
    path('game/', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path, include
from .views import *

app_name = 'game'

urlpatterns = [
    path('list/', game_list, name='game_list'),
    path('attack/', attack, name='attack'),
    path('counter/<int:pk>', counter, name='counter'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('ranking/', ranking, name='ranking'),
    path('detail_ing/<int:pk>', detail_ing, name='detail_ing'),
    path('detail_defend/<int:pk>', detail_defend, name='detail_defend'),
    path('delete/<int:pk>', game_delete, name='game_delete')
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    first_name = None
    last_name = None
    username = models.CharField(max_length=10, unique=True)
    user_score = models.IntegerField(default=0)

    def __str__(self):
        return self.username

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1', 'password2']

common/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from .models import User
from .forms import UserForm

# Create your views here.
def index(request):
    return render(request, 'common/index.html')

def signup(request):
    if (request.method == 'POST'):
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            login(request, user)
            return redirect('/')
    else:
        user_form = UserForm()
    return render(request, 'common/signup.html', {'user_form': user_form})

def logout_page(request):
    logout(request)
    return redirect('/')

templates/common/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section>
    <div class="main_container">
        <div class="main_title">
            <p>Piro Game</p>
        </div>
        {% if user.is_authenticated %}
        <span class="main_username">{{request.user.username}}님이 로그인 중</span>
        {% endif %}
        <div class="btns">
            {% if user.is_authenticated %}
            <button class="btn_game"><a href="{% url 'game:attack' %}">start</a></button>
            <button class="btn_history"><a href="{% url 'game:game_list'%}">list</a></button>
            {% else %}
            <button class="btn_game"><a href="{% url 'common:login' %}">start</a></button>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

templates/common/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block content %}
<section class="submit_container">
    <div class="submit_modal">
        <form method='post', action={% url 'common:login' %}>
            {% csrf_token %}
            <div>
                <label for='username'>ID </label>
                <input id='username' type='text' name='username' value='{{ form.username.value|default_if_none:''}}'>
            </div>
            <div>
                <label for='password'>Password </label>
                <input id='password' type='password' name='password' value='{{ form.password.value|default_if_none:''}}'>
            </div>
            <div class="submit_center">
                <button type='submit' class="submit_btn">로그인</button>
                <input type="hidden" name="next" value="{{ next }}" />
            </div>
            <div class="social-login-button">
                <a href="{% provider_login_url 'github' %}" class="github-login">GitHub</a>
            </div>
            
            <div class="social-login-button">
                <a href="{% provider_login_url 'google' %}" class="google-login">Google</a>
            </div>
            
            <div class="social-login-button">
                <a href="{% provider_login_url 'naver' %}" class="naver-login">Naver</a>
            </div>
            <div class="social-login-button">
                <a href="{% provider_login_url 'kakao' %}" class="kakao-login">Kakao</a>
            </div>
        </form>
    </div>
</section>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %} {% block content %}
<section class="submit_container">
  <div class="submit_modal">
    <form method="POST">
      {% csrf_token %} {{user_form.as_p}}
      <div class="submit_center">
        <button type="submit" class="submit_btn">회원가입하기</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}