common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'common'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', logout_page, name='logout'),
    path('accounts/', include('allauth.urls')),
    
]

#localhost:8000/accounts/github/login
#localhost:8000/accounts/google/login
#localhost:8000/accounts/naver/login
#localhost:8000/accounts/kakao/login

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('common/', include('common.urls')),
    path('game/', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path, include
from .views import *

app_name = 'game'

urlpatterns = [
    path('list/', game_list, name='game_list'),
    path('attack/', attack, name='attack'),
    path('counter/<int:pk>', counter, name='counter'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('ranking/', ranking, name='ranking'),
    path('detail_ing/<int:pk>', detail_ing, name='detail_ing'),
    path('detail_defend/<int:pk>', detail_defend, name='detail_defend'),
    path('delete/<int:pk>', game_delete, name='game_delete')
]

game/forms.py
import random
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from .models import Game, User

class AttackForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ["attacker_card", "defender"]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AttackForm, self).__init__(*args, **kwargs)
        self.shuffleChoices()

    def shuffleChoices(self):
        if self.request:
            random_numbers = sorted(random.sample(range(1, 11), 5))
            choices = [(str(num), str(num)) for num in random_numbers]
            self.fields['attacker_card'] = forms.ChoiceField(choices=choices, widget=forms.RadioSelect,  label="Attacker Card")


    defender = forms.ModelChoiceField(queryset=User.objects.all(), label="Defender")



class CounterForm(forms.ModelForm):
    class Meta:
        model=Game
        fields=['defender_card']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CounterForm, self).__init__(*args, **kwargs)
        self.shuffleChoices()

    def shuffleChoices(self):
        if self.request:
            random_numbers = sorted(random.sample(range(1, 11), 5))
            choices = [(str(num), str(num)) for num in random_numbers]
            self.fields['defender_card'] = forms.ChoiceField(choices=choices, widget=forms.RadioSelect,  label="defender Card")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="{% static 'css/font.css' %}?after">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&family=Lilita+One&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/navbar.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/submit.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}?after" />

    <link rel="stylesheet" href="{% static 'css/game_list.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/game_detail.css' %}?after" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    
    
    <!-- <link
      href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Nanum+Pen+Script&family=Single+Day&display=swap"
      rel="stylesheet"
    /> -->
    <title>피로그래머 카드게임</title>
  </head>
  <body>
    {% include 'navbar.html'%}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    {% include 'footer.html'%}
    <script>
      const attacker_select_card = document.querySelector(".attack-form p:nth-of-type(1) label")
      const attacker_select_enemy = document.querySelector(".attack-form p:nth-of-type(2) label")
      const defender_select_card = document.querySelector(".counter-form p:nth-of-type(1) > label");
      const options = document.querySelectorAll(".attack-form #id_defender option");
      let usernameToDelete = "{{request.user.username}}";
      let delete_option;

      console.log(defender_select_card)

      for (let i = 0; i < options.length; i++) {
        if (options[i].innerHTML == usernameToDelete) {
          delete_option = options[i];
          break; // 해당 옵션을 찾으면 반복문 종료
        }
      }

      if (delete_option) {
        // delete_option이 정의되었을 때 해당 옵션을 삭제하거나 다른 작업 수행
        delete_option.remove(); // 예시로 옵션을 삭제하는 코드
      } else {
        console.error("Option not found!");
      }

      if(attacker_select_card != undefined){
        attacker_select_card.innerHTML = '내가 고른 카드 : '
      }
      if(attacker_select_enemy != undefined){
        attacker_select_enemy.innerHTML = '공격할 상대는? '
      }
      defender_select_card.innerHTML = '반격할 카드 : '
    </script>
  </body>
</html>

templates/footer.html
{% block content %}
    <footer>
        <span>피로그래밍 20기 카드게임 세션 4조</span>
    </footer>
{% endblock %}

templates/navbar.html
{% block content %}
<nav>
    <div id="logo">
        <a href='/'>Pirogrammer Card Game</a>
    </div>
    {% if user.is_authenticated %}
    <div id="nav_menu">
        <a href='{% url "game:attack" %}'>게임하기</a>
        <a href='{% url "game:ranking" %}'>랭킹보기</a>
        <a href={% url "common:logout" %}>로그아웃</a>
    </div>
    {% else %}
    <div id="nav_menu">
        <a href={% url "common:login" %}>로그인</a>
        <a href={% url "common:signup" %}>회원가입</a>
    </div>
    {% endif %}
</nav>
{% endblock %}